### ISSUE TITLE
Getting passwords

### ISSUE THREAD

**Issue by henriquemoody** [kinncj/forker#1]
To fork this repository I had to run this command:

``` bash
./forker forker:fork henriquemoody ***** kinncj forker
```

It's not a good practice to write password in a command line for security reasons. If you use Bash, for example, it will be stored into `.bash_history`. 
Define the password at command line should be optional and since you're using Symfony\Console, you may use the [dialog](http://symfony.com/doc/current/components/console/helpers/dialoghelper.html) helper to get the password if is not defined by command line.
To fix this issue is necessary to change the arguments order, I suggest:

``` bash
./forker forker:fork [ --password=,-p=password ]] [--all,-a] username target [repository]
```

**Comment by kinncj** [comment]
merged on #3
