### ISSUE TITLE
Project goals

### ISSUE THREAD

**Issue by henriquemoody** [kinncj/forker#10]
I wrote [github-sh](https://github.com/henriquemoody/github-sh) years ago (I never finished it) and Forker can have many other useful features like that. I was wondering about the goals of project. What features are in your plans?

**Comment by henriquemoody** [comment]
One month, that says lot about my question :stuck_out_tongue_closed_eyes:

**Comment by kinncj** [comment]
Sorry about that.
Busy :-(

Yes, I do share the same ideas as github-sh.
Even fork gists (since there are tons of snippets as gists around there), and etc.

Share your thoughts.

**Comment by henriquemoody** [comment]
Since this is the case, I will send some pull requests as soon as I possible :smile:

**Comment by henriquemoody** [comment]
Outdated.

PS.: I'm closing my older issues, please reopen if you think it's relevante.

**Comment by kinncj** [comment]
U gotta send the PR :-p

**Comment by henriquemoody** [comment]
But my question was answered :stuck_out_tongue_closed_eyes:

**Comment by kinncj** [comment]
> Since this is the case, I will send some pull requests as soon as I possible

:stuck_out_tongue_closed_eyes:
